// src/components/CartOverlay.vue
<template>
  <div :class="['cart-overlay', { open: open }]" @click="$emit('close')">
    <div class="cart-sheet" @click.stop>
      <div class="sheet-handle"></div>
      
      <!-- Cart Header -->
      <div class="cart-sheet-head">
        <h2>🛒 Your Order</h2>
        <button class="cart-close-btn" @click="$emit('close')">✕</button>
      </div>

      <!-- Cart Items -->
      <div class="cart-sheet-items">
        <div v-if="isLoading" class="cart-loading">
          <p>Loading cart...</p>
        </div>
        <div v-else-if="cartItems.length === 0" class="cart-empty-state">
          <div class="ces-icon">🛒</div>
          <p>Your cart is empty</p>
          <p class="ces-hint">Add items to get started</p>
        </div>
        <CartItem 
          v-for="item in cartItems"
          :key="item.id"
          :item="item"
          @remove="removeItem"
          @update-quantity="updateQuantity"
          :is-loading="itemsLoading.has(item.id)"
        />
      </div>

      <!-- Cart Footer -->
      <div v-if="cartItems.length > 0" class="cart-sheet-footer">
        <div class="sum-row">
          <span>Line items</span>
          <span>{{ cartItems.length }}</span>
        </div>
        <div class="sum-row">
          <span>Total cases</span>
          <span>{{ totalCases }}</span>
        </div>
        <div class="sum-row total">
          <span>Est. total</span>
          <span>${{ cartTotal.toFixed(2) }}</span>
        </div>
        <button class="btn-place-order" @click="$emit('place-order')" :disabled="isLoading">Place Order →</button>
        <button class="btn-clear" @click="clearCart" :disabled="isLoading">Clear cart</button>
      </div>

      <!-- Error message -->
      <div v-if="errorMessage" class="cart-error">
        <p>⚠️ {{ errorMessage }}</p>
      </div>
    </div>
  </div>
</template>

<script>
import CartItem from './CartItem.vue'

export default {
  name: 'CartOverlay',
  components: {
    CartItem
  },
  props: {
    open: {
      type: Boolean,
      default: false
    },
    jwt: {
      type: String,
      required: true
    }
  },
  emits: ['close', 'place-order', 'cart-updated'],
  data() {
    return {
      cartItems: [],
      isLoading: false,
      itemsLoading: new Set(),
      errorMessage: null
    }
  },
  computed: {
    cartTotal() {
      return this.cartItems.reduce((sum, item) => sum + (parseFloat(item.price) * item.quantity), 0)
    },
    totalCases() {
      return this.cartItems.reduce((sum, item) => sum + item.quantity, 0)
    }
  },
  watch: {
    open(newVal) {
      if (newVal) {
        this.loadCart();
      }
    }
  },
  methods: {
    async loadCart() {
      this.isLoading = true;
      this.errorMessage = null;
      try {
        const response = await fetch('/api/cart', {
          method: 'GET',
          headers: {
            'Authorization': `Bearer ${this.jwt}`,
            'Content-Type': 'application/json'
          }
        });

        if (!response.ok) {
          throw new Error('Failed to load cart');
        }

        const data = await response.json();
        this.cartItems = data.items || [];
        this.$emit('cart-updated', { items: this.cartItems, total: data.total_cost });
      } catch (err) {
        console.error('Load cart error:', err);
        this.errorMessage = 'Failed to load cart. Please try again.';
      } finally {
        this.isLoading = false;
      }
    },

    async removeItem(itemId) {
      this.itemsLoading.add(itemId);
      try {
        const response = await fetch(`/api/cart/items/${itemId}`, {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${this.jwt}`,
            'Content-Type': 'application/json'
          }
        });

        if (!response.ok) {
          throw new Error('Failed to remove item');
        }

        const data = await response.json();
        this.cartItems = data.items || [];
        this.$emit('cart-updated', { items: this.cartItems, total: data.total_cost });
      } catch (err) {
        console.error('Remove item error:', err);
        this.errorMessage = 'Failed to remove item. Please try again.';
      } finally {
        this.itemsLoading.delete(itemId);
      }
    },

    async updateQuantity(itemId, quantity) {
      this.itemsLoading.add(itemId);
      try {
        const response = await fetch(`/api/cart/items/${itemId}`, {
          method: 'PUT',
          headers: {
            'Authorization': `Bearer ${this.jwt}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({ quantity })
        });

        if (!response.ok) {
          throw new Error('Failed to update quantity');
        }

        const data = await response.json();
        this.cartItems = data.items || [];
        this.$emit('cart-updated', { items: this.cartItems, total: data.total_cost });
      } catch (err) {
        console.error('Update quantity error:', err);
        this.errorMessage = 'Failed to update quantity. Please try again.';
      } finally {
        this.itemsLoading.delete(itemId);
      }
    },

    async clearCart() {
      if (!confirm('Are you sure you want to clear your entire cart?')) {
        return;
      }

      this.isLoading = true;
      try {
        const response = await fetch('/api/cart', {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${this.jwt}`,
            'Content-Type': 'application/json'
          }
        });

        if (!response.ok) {
          throw new Error('Failed to clear cart');
        }

        const data = await response.json();
        this.cartItems = data.items || [];
        this.$emit('cart-updated', { items: this.cartItems, total: data.total_cost });
      } catch (err) {
        console.error('Clear cart error:', err);
        this.errorMessage = 'Failed to clear cart. Please try again.';
      } finally {
        this.isLoading = false;
      }
    }
  },
  mounted() {
    if (this.open) {
      this.loadCart();
    }
  }
}
</script>

<style scoped>
:root {
  --bg: #f5f4f0;
  --surface: #fff;
  --card2: #faf9f7;
  --border: #e2ddd8;
  --red: #c0392b;
  --text: #1a1a18;
  --sub: #5a5750;
  --muted: #9a948c;
  --faint: #d4cfc9;
  --shadow: 0 1px 3px rgba(0,0,0,0.07), 0 4px 12px rgba(0,0,0,0.04);
  --shadow-lg: 0 20px 60px rgba(0,0,0,0.18);
}

.cart-overlay {
  position: fixed;
  inset: 0;
  background: rgba(26,26,24,0);
  z-index: 500;
  display: flex;
  align-items: flex-end;
  justify-content: center;
  pointer-events: none;
  transition: background 0.3s ease;
}

.cart-overlay.open {
  background: rgba(26,26,24,0.45);
  pointer-events: all;
}

.cart-sheet {
  background: var(--surface);
  border-radius: 20px 20px 0 0;
  width: 100%;
  max-width: 600px;
  overflow: hidden;
  box-shadow: var(--shadow-lg);
  transform: translateY(100%);
  transition: transform 0.35s cubic-bezier(.32,1,.32,1);
  max-height: 92vh;
  display: flex;
  flex-direction: column;
}

.cart-overlay.open .cart-sheet {
  transform: translateY(0);
}

.sheet-handle {
  width: 38px;
  height: 4px;
  background: var(--faint);
  border-radius: 2px;
  margin: 10px auto 0;
  flex-shrink: 0;
}

.cart-sheet-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px 14px;
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
}

.cart-sheet-head h2 {
  font-size: 16px;
  font-weight: 600;
  color: var(--text);
  letter-spacing: -0.3px;
  margin: 0;
}

.cart-close-btn {
  width: 28px;
  height: 28px;
  border-radius: 8px;
  border: 1px solid var(--border);
  background: var(--bg);
  color: var(--muted);
  font-size: 14px;
  cursor: pointer;
  transition: all 0.15s;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
}

.cart-close-btn:hover {
  background: var(--red-light);
  border-color: var(--red-mid);
  color: var(--red);
}

.cart-sheet-items {
  flex: 1;
  overflow-y: auto;
  padding: 10px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.cart-empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
  text-align: center;
  color: var(--muted);
}

.ces-icon {
  font-size: 48px;
  margin-bottom: 14px;
  opacity: 0.4;
}

.cart-empty-state p {
  margin: 0;
  font-size: 14px;
}

.ces-hint {
  font-size: 12px !important;
  color: var(--faint);
  margin-top: 6px !important;
}

.cart-sheet-footer {
  padding: 12px 16px;
  border-top: 1px solid var(--border);
  background: var(--card2);
  flex-shrink: 0;
}

.sum-row {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  color: var(--sub);
  margin-bottom: 4px;
}

.sum-row.total {
  color: var(--text);
  font-weight: 600;
  font-size: 13px;
  border-top: 1px solid var(--border);
  padding-top: 6px;
  margin-top: 2px;
}

.btn-place-order {
  width: 100%;
  padding: 12px;
  background: var(--red);
  border: none;
  border-radius: 8px;
  color: #fff;
  font-family: 'DM Sans', sans-serif;
  font-weight: 600;
  font-size: 14px;
  cursor: pointer;
  margin-top: 10px;
  transition: all 0.18s;
  letter-spacing: -0.2px;
}

.btn-place-order:hover {
  background: #a93226;
}

.btn-clear {
  width: 100%;
  padding: 8px;
  background: transparent;
  border: 1px solid var(--border);
  border-radius: 8px;
  color: var(--sub);
  font-family: 'DM Sans', sans-serif;
  font-size: 13px;
  cursor: pointer;
  margin-top: 6px;
  transition: all 0.15s;
}

.btn-clear:hover {
  border-color: var(--red);
  color: var(--red);
}

.btn-place-order:disabled,
.btn-clear:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.cart-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
  color: var(--muted);
  font-size: 14px;
}

.cart-error {
  background: #fee;
  border-top: 1px solid var(--border);
  padding: 10px 16px;
  color: var(--red);
  font-size: 12px;
  flex-shrink: 0;
}

.cart-error p {
  margin: 0;
}
</style>

// components/CartOverlay.jsx
'use client';
import React, { useState } from 'react'
import { X, Minus, Plus, ShoppingCart, ArrowRight } from 'lucide-react'

function CartItem({ item, isLoading, onRemove, onUpdateQty, showPrices = true }) {
  const name = item.product_name || item.name
  const quantity = item.quantity || item.qty || 1
  const price = parseFloat(item.price) || 0
  const unit = item.unit || 'cases'
  const casesPerPallet = parseInt(item.cases_per_pallet) || 60
  const totalCases = unit === 'pallets' ? quantity * casesPerPallet : quantity
  const totalPrice = unit === 'pallets' ? price * totalCases : price * quantity
  const [localQty, setLocalQty] = useState(quantity)

  React.useEffect(() => { setLocalQty(item.quantity || item.qty || 1) }, [item.quantity, item.qty])

  const decrement = () => { if (localQty > 1) { const nq = localQty - 1; setLocalQty(nq); onUpdateQty(item.id, nq) } }
  const increment = () => { const nq = localQty + 1; setLocalQty(nq); onUpdateQty(item.id, nq) }
  const handleInputChange = (e) => { const v = parseInt(e.target.value, 10); if (!isNaN(v) && v > 0) setLocalQty(v); else if (e.target.value === '') setLocalQty('') }
  const handleInputBlur = () => { const v = parseInt(localQty, 10); if (!isNaN(v) && v > 0) { if (v !== quantity) onUpdateQty(item.id, v) } else setLocalQty(quantity) }
  const handleKeyDown = (e) => { if (e.key === 'Enter') e.target.blur() }

  return (
    <div className={`p-3 bg-white rounded-lg border border-slate-200 mb-1 shadow-sm transition-opacity max-sm:p-2.5 ${isLoading ? 'opacity-60 pointer-events-none' : ''}`}>
      {/* Top row: image + name + remove button */}
      <div className="flex gap-3 items-start max-sm:gap-2">
        <div className="shrink-0 bg-slate-50 rounded-md overflow-hidden border border-slate-200 flex items-center justify-center" style={{ width: 'clamp(48px, 5em, 80px)', height: 'clamp(48px, 5em, 80px)' }}>
          {item.image_url
            ? <img src={item.image_url} alt={name} className="w-full h-full object-contain p-1" />
            : <div className="text-slate-400" style={{ fontSize: 'clamp(9px, 0.7em, 12px)' }}>No img</div>
          }
        </div>
        <div className="flex-1 min-w-0">
          <div className="font-medium text-slate-800 leading-tight mb-0.5 overflow-hidden text-ellipsis whitespace-nowrap" style={{ fontSize: 'clamp(12px, 1em, 16px)' }}>{name}</div>
          <div className="text-slate-400 leading-tight mb-1 overflow-hidden text-ellipsis whitespace-nowrap" style={{ fontSize: 'clamp(10px, 0.75em, 13px)' }}>
            {item.weight || ''}{item.bags_per_case && <> &middot; {item.bags_per_case}</>}
          </div>
          {showPrices && <div className="font-semibold text-indigo-500" style={{ fontSize: 'clamp(11px, 0.85em, 15px)' }}>${price.toFixed(2)}</div>}
        </div>
        <button onClick={() => onRemove(item.id)} disabled={isLoading}
          className="rounded bg-slate-100 text-slate-400 border-none cursor-pointer flex items-center justify-center transition-colors hover:bg-red-500 hover:text-white shrink-0" style={{ width: 'clamp(24px, 1.8em, 32px)', height: 'clamp(24px, 1.8em, 32px)' }}>
          <X style={{ width: 'clamp(12px, 0.9em, 16px)', height: 'clamp(12px, 0.9em, 16px)' }} />
        </button>
      </div>
      {/* Bottom row: qty controls + total */}
      <div className="flex items-center justify-between mt-2 pt-2 border-t border-slate-100">
        <div className="flex items-center gap-0">
          <button onClick={decrement} disabled={isLoading || quantity <= 1}
            className="border-none bg-transparent text-slate-500 font-semibold cursor-pointer flex items-center justify-center transition-colors hover:text-indigo-500 disabled:opacity-30 disabled:cursor-not-allowed" style={{ width: 'clamp(28px, 2em, 36px)', height: 'clamp(28px, 2em, 36px)' }}>
            <Minus style={{ width: 'clamp(14px, 1.1em, 20px)', height: 'clamp(14px, 1.1em, 20px)' }} />
          </button>
          <input type="number" value={localQty} onChange={handleInputChange} onBlur={handleInputBlur} onKeyDown={handleKeyDown}
            disabled={isLoading} min="1"
            className="border border-slate-200 bg-white rounded-md text-center font-semibold text-slate-800 p-0 focus:outline-none focus:border-indigo-400" style={{ width: 'clamp(38px, 3em, 50px)', height: 'clamp(28px, 2em, 36px)', fontSize: 'clamp(13px, 1em, 17px)' }} />
          <button onClick={increment} disabled={isLoading}
            className="border-none bg-transparent text-slate-500 font-semibold cursor-pointer flex items-center justify-center transition-colors hover:text-indigo-500 disabled:opacity-30" style={{ width: 'clamp(28px, 2em, 36px)', height: 'clamp(28px, 2em, 36px)' }}>
            <Plus style={{ width: 'clamp(14px, 1.1em, 20px)', height: 'clamp(14px, 1.1em, 20px)' }} />
          </button>
          <span className="text-slate-500 font-medium ml-2" style={{ fontSize: 'clamp(11px, 0.8em, 14px)' }}>{unit}{unit === 'pallets' ? ` (${totalCases} cs)` : ''}</span>
        </div>
        {showPrices && price > 0 && <span className="font-bold text-slate-800" style={{ fontSize: 'clamp(14px, 1.1em, 18px)' }}>${totalPrice.toFixed(2)}</span>}
      </div>
    </div>
  )
}

function CartOverlay({ isOpen, cartItems = [], onClose, onRemoveItem, onPlaceOrder, onClearCart, onUpdateQty, showPrices = true }) {
  const [dragY, setDragY] = useState(0)
  const dragStart = React.useRef(0)
  const dragging = React.useRef(false)
  const scrollRef = React.useRef(null)
  const canDrag = React.useRef(false)
  const onTouchStart = (e) => {
    dragStart.current = e.touches[0].clientY
    dragging.current = true
    canDrag.current = !scrollRef.current || scrollRef.current.scrollTop <= 0
  }
  const onTouchMove = (e) => {
    if (!dragging.current) return
    const diff = e.touches[0].clientY - dragStart.current
    if (diff < 0) { canDrag.current = false; setDragY(0); return }
    if (!canDrag.current && scrollRef.current && scrollRef.current.scrollTop <= 0) {
      canDrag.current = true
      dragStart.current = e.touches[0].clientY
      return
    }
    if (canDrag.current && diff > 0) setDragY(diff)
  }
  const onTouchEnd = () => {
    dragging.current = false
    if (dragY > 100) {
      // Animate all the way down, then trigger close
      setDragY(typeof window !== 'undefined' ? window.innerHeight : 800)
      setTimeout(() => {
        dragging.current = true // Disable transition so translateY(100%) switch is instant
        onClose()
      }, 380)
    } else {
      setDragY(0)
    }
  }
  React.useEffect(() => { if (!isOpen) setDragY(0) }, [isOpen])

  const cartTotal = cartItems.reduce((sum, item) => {
    const price = parseFloat(item.price) || 0
    const qty = item.quantity || item.qty || 1
    const u = item.unit || 'cases'
    const cpp = parseInt(item.cases_per_pallet) || 60
    const cases = u === 'pallets' ? qty * cpp : qty
    return sum + price * cases
  }, 0)

  const totalCases = cartItems.reduce((sum, item) => {
    const qty = item.quantity || item.qty || 1
    const u = item.unit || 'cases'
    const cpp = parseInt(item.cases_per_pallet) || 60
    return sum + (u === 'pallets' ? qty * cpp : qty)
  }, 0)

  const handleUpdateQty = (itemId, newQty) => { if (onUpdateQty) onUpdateQty(itemId, newQty) }

  return (
    <div className={`fixed inset-0 z-[10000] flex items-end justify-center transition-colors duration-300
      ${isOpen ? 'bg-black/40' : 'bg-transparent'}`}
      style={{ pointerEvents: isOpen ? 'auto' : 'none', touchAction: isOpen ? 'none' : 'auto', overscrollBehavior: 'none' }}
      onClick={onClose}>
      <div className={`bg-white rounded-t-2xl w-full max-w-[700px] overflow-hidden shadow-2xl flex flex-col
        max-sm:max-w-full max-sm:rounded-t-xl max-sm:h-[75vh] max-sm:max-h-[75vh]
        ${!isOpen ? 'pointer-events-none' : ''}`}
        style={{ maxHeight: '92vh', transform: !isOpen ? 'translateY(100%)' : `translateY(${dragY}px)`, transition: dragging.current ? 'none' : 'transform 0.35s cubic-bezier(.32,1,.32,1)', willChange: 'transform', fontSize: 'clamp(14px, 1vw, 18px)' }}
        onClick={(e) => e.stopPropagation()}
        onTouchStart={onTouchStart} onTouchMove={onTouchMove} onTouchEnd={onTouchEnd}>

        {/* Handle */}
        <div className="shrink-0 flex justify-center items-center pt-2 pb-2">
          <div className="w-10 h-1 bg-slate-300 rounded-full" />
        </div>

        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-slate-200 shrink-0 max-sm:px-3.5">
          <h2 className="font-semibold text-slate-800 m-0" style={{ fontSize: 'clamp(16px, 1.2em, 22px)' }}>Your Order</h2>
          <button onClick={onClose}
            className="rounded-lg border border-slate-200 bg-slate-50 text-slate-400 flex items-center justify-center cursor-pointer transition-colors hover:bg-indigo-500 hover:border-indigo-500 hover:text-white" style={{ width: 'clamp(28px, 2.2em, 36px)', height: 'clamp(28px, 2.2em, 36px)' }}>
            <X style={{ width: 'clamp(14px, 1em, 18px)', height: 'clamp(14px, 1em, 18px)' }} />
          </button>
        </div>

        {/* Items */}
        <div ref={scrollRef} className="flex-1 overflow-y-auto p-2.5 flex flex-col gap-1.5 max-sm:p-2 max-sm:gap-1">
          {cartItems.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 text-slate-400">
              <ShoppingCart className="w-12 h-12 mb-3.5 opacity-40" />
              <p className="m-0 text-sm">Your cart is empty</p>
              <p className="m-0 mt-1.5 text-xs text-slate-300">Add items to get started</p>
            </div>
          ) : (
            cartItems.map((item) => (
              <CartItem key={item.id} item={item} isLoading={false} onRemove={onRemoveItem} onUpdateQty={handleUpdateQty} showPrices={showPrices} />
            ))
          )}
        </div>

        {/* Footer */}
        {cartItems.length > 0 && (
          <div className="px-4 py-3 border-t border-slate-200 bg-slate-50 shrink-0 max-sm:px-3.5 max-sm:pb-3.5">
            <div className="flex justify-between text-slate-500 mb-1" style={{ fontSize: 'clamp(12px, 0.85em, 15px)' }}><span>Line items</span><span>{cartItems.length}</span></div>
            <div className="flex justify-between text-slate-500 mb-1" style={{ fontSize: 'clamp(12px, 0.85em, 15px)' }}><span>Total cases</span><span>{totalCases}</span></div>
            {showPrices && (
              <div className="flex justify-between text-slate-800 font-semibold border-t border-slate-200 pt-1.5 mt-0.5" style={{ fontSize: 'clamp(14px, 1.1em, 18px)' }}>
                <span>Est. total</span><span>${cartTotal.toFixed(2)}</span>
              </div>
            )}
            <button onClick={onPlaceOrder}
              className="w-full bg-indigo-500 border-none rounded-lg text-white font-semibold cursor-pointer mt-2.5 transition-colors hover:bg-indigo-600 flex items-center justify-center gap-2" style={{ padding: 'clamp(10px, 0.9em, 16px)', fontSize: 'clamp(14px, 1em, 17px)' }}>
              Place Order <ArrowRight style={{ width: 'clamp(16px, 1.1em, 20px)', height: 'clamp(16px, 1.1em, 20px)' }} />
            </button>
            <button onClick={onClearCart}
              className="w-full bg-transparent border border-slate-200 rounded-lg text-slate-500 cursor-pointer mt-1.5 transition-colors hover:border-red-300 hover:text-red-500" style={{ padding: 'clamp(8px, 0.7em, 12px)', fontSize: 'clamp(13px, 0.9em, 16px)' }}>
              Clear cart
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

export default CartOverlay
