// src/components/CategorySidebar.vue
<template>
  <div class="category-sidebar">
    <div class="sidebar-header">
      <h2>Categories</h2>
      <button v-if="hierarchyLoaded" @click="expandAll" class="btn-expand-all" title="Expand all">
        <span>{{ allExpanded ? '↕' : '↕' }}</span>
      </button>
    </div>

    <div v-if="loading" class="sidebar-loading">
      <span class="spinner"></span>
      Loading categories...
    </div>

    <div v-else-if="error" class="sidebar-error">
      <p>⚠️ Error loading categories</p>
      <small>{{ error }}</small>
    </div>

    <ul v-else class="category-list">
      <li v-for="superCat in hierarchy" :key="superCat.id" class="super-category-item">
        <div class="super-category-header" @click="toggleSuper(superCat.id)">
          <span class="expand-icon" :class="{ expanded: expandedSupers.has(superCat.id) }">
            ▶
          </span>
          <span class="emoji">{{ superCat.emoji }}</span>
          <span class="name">{{ superCat.name }}</span>
          <span class="count">({{ superCat.totalProducts }})</span>
        </div>

        <ul
          v-show="expandedSupers.has(superCat.id)"
          class="sub-categories"
          :class="{ visible: expandedSupers.has(superCat.id) }"
        >
          <li
            v-for="subCat in superCat.categories"
            :key="subCat.id"
            class="sub-category-item"
            @click="selectCategory(subCat)"
          >
            <span class="subcategory-name">{{ subCat.name }}</span>
            <span class="sub-product-count">{{ subCat.productCount }}</span>
          </li>
        </ul>
      </li>
    </ul>

    <div v-if="hierarchyLoaded && !loading" class="sidebar-footer">
      <small>{{ totalAllProducts }} products</small>
    </div>
  </div>
</template>

<script>
export default {
  name: 'CategorySidebar',
  props: {
    token: {
      type: String,
      default: null
    }
  },
  emits: ['category-selected'],
  data() {
    return {
      hierarchy: [],
      expandedSupers: new Set(),
      loading: true,
      error: null,
      hierarchyLoaded: false
    };
  },
  computed: {
    allExpanded() {
      return this.expandedSupers.size === this.hierarchy.length && this.hierarchy.length > 0;
    },
    totalAllProducts() {
      return this.hierarchy.reduce((sum, cat) => sum + cat.totalProducts, 0);
    }
  },
  methods: {
    async loadHierarchy() {
      this.loading = true;
      this.error = null;

      try {
        const headers = {};
        if (this.token) {
          headers['Authorization'] = `Bearer ${this.token}`;
        }

        const response = await fetch('/api/categories/hierarchy', { headers });
        if (!response.ok) throw new Error('Failed to load categories');

        const data = await response.json();
        if (!data.success) throw new Error(data.error || 'Failed to load categories');

        this.hierarchy = data.hierarchy;
        this.hierarchyLoaded = true;

        // Auto-expand first category
        if (this.hierarchy.length > 0) {
          this.expandedSupers.add(this.hierarchy[0].id);
        }
      } catch (err) {
        console.error('Error loading hierarchy:', err);
        this.error = err.message;
      } finally {
        this.loading = false;
      }
    },
    toggleSuper(id) {
      if (this.expandedSupers.has(id)) {
        this.expandedSupers.delete(id);
      } else {
        this.expandedSupers.add(id);
      }
      // Trigger reactivity
      this.expandedSupers = new Set(this.expandedSupers);
    },
    expandAll() {
      if (this.allExpanded) {
        this.expandedSupers.clear();
      } else {
        this.hierarchy.forEach(cat => {
          this.expandedSupers.add(cat.id);
        });
      }
      this.expandedSupers = new Set(this.expandedSupers);
    },
    selectCategory(category) {
      this.$emit('category-selected', category);
    }
  },
  mounted() {
    this.loadHierarchy();
  }
};
</script>

<style scoped>
.category-sidebar {
  background: var(--sidebar-bg, #fff);
  border-right: 1px solid var(--border, #e2ddd8);
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  font-family: 'DM Sans', sans-serif;
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  border-bottom: 1px solid var(--border, #e2ddd8);
  flex-shrink: 0;
}

.sidebar-header h2 {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--text, #1a1a18);
}

.btn-expand-all {
  background: transparent;
  border: none;
  cursor: pointer;
  font-size: 14px;
  color: var(--muted, #9a948c);
  padding: 4px 8px;
  border-radius: 4px;
  transition: all 0.2s;
}

.btn-expand-all:hover {
  background: var(--bg, #f5f4f0);
  color: var(--text, #1a1a18);
}

.sidebar-loading,
.sidebar-error {
  padding: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: var(--muted, #9a948c);
  font-size: 13px;
}

.spinner {
  display: inline-block;
  width: 16px;
  height: 16px;
  border: 2px solid var(--border, #e2ddd8);
  border-top-color: var(--red, #c0392b);
  border-radius: 50%;
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.sidebar-error {
  color: #c0392b;
}

.sidebar-error small {
  color: var(--muted, #9a948c);
}

.category-list {
  list-style: none;
  margin: 0;
  padding: 0;
  overflow-y: auto;
  flex: 1;
}

.super-category-item {
  border-bottom: 1px solid var(--border2, #ede9e4);
}

.super-category-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  cursor: pointer;
  user-select: none;
  transition: background 0.15s;
  font-weight: 500;
  font-size: 13px;
  color: var(--text, #1a1a18);
}

.super-category-header:hover {
  background: var(--bg, #f5f4f0);
}

.expand-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  transition: transform 0.2s;
  color: var(--muted, #9a948c);
  font-size: 10px;
}

.expand-icon.expanded {
  transform: rotate(90deg);
}

.emoji {
  font-size: 14px;
  width: 20px;
  text-align: center;
}

.super-category-header .name {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.count {
  font-size: 11px;
  color: var(--muted, #9a948c);
  font-weight: 400;
}

.sub-categories {
  list-style: none;
  margin: 0;
  padding: 0;
  background: var(--card2, #faf9f7);
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}

.sub-categories.visible {
  max-height: 800px;
}

.sub-category-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 16px 10px 40px;
  font-size: 12px;
  color: var(--sub, #5a5750);
  cursor: pointer;
  transition: all 0.15s;
  border-left: 3px solid transparent;
}

.sub-category-item:hover {
  background: var(--bg, #f5f4f0);
  color: var(--text, #1a1a18);
  border-left-color: var(--red, #c0392b);
}

.subcategory-name {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.sub-product-count {
  font-size: 11px;
  color: var(--muted, #9a948c);
  margin-left: 8px;
  flex-shrink: 0;
}

.sidebar-footer {
  padding: 12px 16px;
  border-top: 1px solid var(--border, #e2ddd8);
  text-align: center;
  color: var(--muted, #9a948c);
  font-size: 11px;
  flex-shrink: 0;
}
</style>

// components/CategorySidebar.jsx
'use client';
import React, { useState, useEffect, useMemo } from 'react'

function CategorySidebar({ isOpen, onClose, onSelectCategory, token }) {
  const [hierarchy, setHierarchy] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [expandedSuper, setExpandedSuper] = useState(null)
  const [selectedId, setSelectedId] = useState(null)
  const [searchQuery, setSearchQuery] = useState('')

  const emojiMap = {
    'Chips & Savory Snacks': '\uD83E\uDD54',
    'Noodles & Rice': '\uD83C\uDF5C',
    'Cookies & Wafers': '\uD83C\uDF6A',
    'Candy & Jelly': '\uD83C\uDF6C',
    'Ice Cream': '\uD83C\uDF66',
    'Beverages': '\uD83E\uDD64',
    'Korean Snacks': '\uD83C\uDDF0\uD83C\uDDF7'
  }

  useEffect(() => {
    loadHierarchy()
  }, [token])

  const loadHierarchy = async () => {
    setLoading(true)
    setError(null)
    try {
      const headers = {}
      if (token) headers['Authorization'] = `Bearer ${token}`
      const response = await fetch('/api/categories/hierarchy', { headers })
      if (!response.ok) throw new Error('Failed to load categories')
      const data = await response.json()
      if (!data.success) throw new Error(data.error || 'Failed to load categories')
      setHierarchy(data.hierarchy || [])
    } catch (err) {
      console.error('Error loading hierarchy:', err)
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const totalProducts = hierarchy.reduce((sum, cat) => sum + (cat.totalProducts || 0), 0)

  const filteredHierarchy = useMemo(() => {
    if (!searchQuery) return hierarchy
    const q = searchQuery.toLowerCase()
    return hierarchy.filter(sc =>
      sc.name.toLowerCase().includes(q) ||
      sc.categories?.some(c => c.name.toLowerCase().includes(q))
    )
  }, [hierarchy, searchQuery])

  const getEmoji = (name) => emojiMap[name] || '\uD83D\uDCE6'

  const selectAll = () => {
    setSelectedId(null)
    setExpandedSuper(null)
    onSelectCategory(null)
  }

  const toggleSuper = (superCat) => {
    if (expandedSuper === superCat.name) {
      setExpandedSuper(null)
    } else {
      setExpandedSuper(superCat.name)
    }
  }

  const selectSub = (subCat) => {
    setSelectedId(subCat.id || subCat.name)
    onSelectCategory(subCat)
  }

  return (
    <>
      <div className={`sidebar-overlay ${isOpen ? 'open' : ''}`} onClick={onClose}></div>
      <aside className={`sidebar${isOpen ? ' open-mobile' : ' collapsed'}`}>
        <div className="sb-top">
          <div className="sb-label">Browse</div>
        </div>
        <div className="sb-search">
          <input
            type="text"
            placeholder="Search Categories..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
          />
        </div>

        {loading ? (
          <div className="sb-loading"><span className="sb-spinner"></span> Loading...</div>
        ) : error ? (
          <div className="sb-loading" style={{ color: '#c0392b' }}>{'\u26A0\uFE0F'} {error}</div>
        ) : (
          <>
            <div className={`sb-all ${selectedId === null ? 'active' : ''}`} onClick={selectAll}>
              <span style={{ fontSize: 14 }}>{'\uD83D\uDCE6'}</span> All Products
              <span className="a-count">{totalProducts}</span>
            </div>
            <div className="sb-divider"></div>
            <div className="sb-categories">
              {filteredHierarchy.map(superCat => (
                <div key={superCat.id} className="sb-super-group">
                  <div
                    className={`sb-super-btn ${expandedSuper === superCat.name ? 'active open' : ''}`}
                    onClick={() => toggleSuper(superCat)}
                  >
                    <span className="s-emoji">{superCat.emoji || getEmoji(superCat.name)}</span>
                    <span className="s-label">{superCat.name}</span>
                    <span className="s-cnt">{superCat.totalProducts}</span>
                    <span className="s-arr">{expandedSuper === superCat.name ? '\u25BC' : '\u203A'}</span>
                  </div>
                  <div className={`sb-cats ${expandedSuper === superCat.name ? 'open' : ''}`}>
                    {superCat.categories?.map(subCat => (
                      <div
                        key={subCat.id}
                        className={`sb-cat ${selectedId === (subCat.id || subCat.name) ? 'active' : ''}`}
                        onClick={() => selectSub(subCat)}
                      >
                        <span className="sc-label">{subCat.name}</span>
                        <span className="sc-cnt">{subCat.productCount}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
              {filteredHierarchy.length === 0 && (
                <div className="sb-loading">No categories found</div>
              )}
            </div>
          </>
        )}
      </aside>

      <style jsx>{`
        .sidebar-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.25); z-index: 150; display: none; top: 56px; }
        @media (max-width: 768px) {
          .sidebar-overlay.open { display: block; }
        }
        .sidebar { width: 236px; min-width: 236px; background: var(--surface); border-right: 1px solid var(--border); overflow-y: auto; height: calc(100vh - 56px); position: sticky; top: 56px; transition: transform 0.28s cubic-bezier(.4,0,.2,1), margin-left 0.28s cubic-bezier(.4,0,.2,1); z-index: 160; flex-shrink: 0; }
        .sidebar.collapsed { margin-left: -236px; }
        .sb-top { padding: 14px 14px 6px; }
        .sb-label { font-size: 10px; font-weight: 600; letter-spacing: 1px; text-transform: uppercase; color: var(--muted); margin-bottom: 8px; }
        .sb-search { padding: 0 10px 10px; }
        .sb-search input { width: 100%; padding: 7px 11px; background: var(--bg); border: 1px solid var(--border); border-radius: 8px; color: var(--text); font-family: 'DM Sans', sans-serif; font-size: 13px; outline: none; transition: border-color 0.15s; box-sizing: border-box; }
        .sb-search input:focus { border-color: var(--red); }
        .sb-search input::placeholder { color: var(--muted); }
        .sb-all { display: flex; align-items: center; gap: 10px; padding: 14px 14px; cursor: pointer; font-size: 14px; color: var(--sub); font-weight: 500; transition: all 0.15s; background: var(--bg); border-bottom: 1px solid var(--border); }
        .sb-all:hover { background: var(--border2); color: var(--text); }
        .sb-all.active { color: var(--red); background: var(--red-light); }
        .a-count { margin-left: auto; font-size: 11px; color: var(--muted); background: var(--surface); padding: 2px 8px; border-radius: 20px; border: 1px solid var(--border); }
        .sb-divider { height: 1px; background: var(--border); margin: 0; }
        .sb-categories { display: flex; flex-direction: column; }
        .sb-super-btn { width: 100%; display: flex; align-items: center; gap: 10px; padding: 14px 14px; border: none; background: var(--bg); color: var(--sub); cursor: pointer; font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500; text-align: left; transition: all 0.15s; border-bottom: 1px solid var(--border); }
        .sb-super-btn:hover { background: var(--border2); color: var(--text); }
        .sb-super-btn.active { color: var(--red); background: var(--red-light); }
        .sb-super-btn .s-emoji { font-size: 16px; width: 20px; text-align: center; flex-shrink: 0; }
        .sb-super-btn .s-label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .sb-super-btn .s-cnt { font-size: 11px; color: var(--muted); background: var(--surface); padding: 2px 8px; border-radius: 20px; border: 1px solid var(--border); }
        .sb-super-btn .s-arr { font-size: 10px; color: var(--faint); transition: transform 0.2s; flex-shrink: 0; }
        .sb-super-btn.open .s-arr { transform: rotate(90deg); }
        .sb-cats { overflow: hidden; max-height: 0; transition: max-height 0.25s ease; }
        .sb-cats.open { max-height: 700px; }
        .sb-cat { display: flex; align-items: center; justify-content: space-between; padding: 10px 14px 10px 44px; cursor: pointer; font-size: 13px; color: var(--sub); transition: all 0.15s; background: var(--surface); border-bottom: 1px solid var(--border2); }
        .sb-cat:hover { background: var(--bg); color: var(--text); }
        .sb-cat.active { color: var(--red); background: var(--red-light); font-weight: 500; }
        .sc-label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .sc-cnt { font-size: 11px; color: var(--muted); }
        .sb-loading { padding: 16px; text-align: center; color: var(--muted); font-size: 13px; }
        .sb-spinner { display: inline-block; width: 14px; height: 14px; border: 2px solid var(--border); border-top-color: var(--red); border-radius: 50%; animation: spin 0.6s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }
        @media (max-width: 768px) {
          .sidebar { position: fixed; left: 0; top: 56px; transform: translateX(-100%); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
          .sidebar.open-mobile { transform: translateX(0); }
        }
      `}</style>
    </>
  )
}

export default CategorySidebar
