// components/CategoryView.jsx
'use client';
import React, { useState, useEffect, useMemo } from 'react'
import ProductCard from './ProductCard'

function useIsMobile() {
  const [m, setM] = useState(false)
  useEffect(() => { const c = () => setM(window.innerWidth <= 640); c(); window.addEventListener('resize', c); return () => window.removeEventListener('resize', c) }, [])
  return m
}

function CategoryView({ products, favorites, cart, onProductSelected, onAddToCart, onToggleFavorite, cardSize }) {
  const isMobile = useIsMobile()
  const [hierarchy, setHierarchy] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => { loadCategories() }, [])

  const loadCategories = async () => {
    try {
      setLoading(true)
      const response = await fetch('/api/categories/hierarchy')
      if (!response.ok) throw new Error('Failed to load categories')
      const data = await response.json()
      setHierarchy(data.hierarchy || [])
      setError(null)
    } catch (err) {
      setError('Error loading categories: ' + err.message)
      console.error('CategoryView error:', err)
    } finally { setLoading(false) }
  }

  const isFavorited = (productId) => favorites.some(fav => fav.id === productId)
  const isInCart = (productId) => cart.some(item => item.id === productId)

  const getProductsByCategory = (superCatId) => {
    const grouped = {}
    products.forEach(product => {
      if (product.super_category_id !== superCatId) return
      const catId = product.category_id || 'uncategorized'
      const catName = product.category || 'Uncategorized'
      if (!grouped[catId]) grouped[catId] = { id: catId, name: catName, products: [] }
      grouped[catId].products.push(product)
    })
    return Object.values(grouped)
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(cat => ({ ...cat, products: cat.products.sort((a, b) => a.name.localeCompare(b.name)) }))
  }

  if (loading) return <div className="p-10 text-center text-base text-slate-400">Loading categories...</div>
  if (error) return <div className="p-10 text-center text-base text-red-500">{error}</div>

  return (
    <div className="w-full p-5">
      {hierarchy.map(superCat => {
        const catSections = getProductsByCategory(superCat.id)
        if (catSections.length === 0) return null

        return (
          <div key={superCat.id} id={`supercat-${superCat.id}`} className="mb-10">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b-2 border-slate-200">
              <span className="text-[28px]">{superCat.emoji}</span>
              <h2 className="text-2xl font-semibold text-slate-800 m-0 max-sm:text-lg">{superCat.name}</h2>
              <span className="text-base text-slate-500 ml-auto">({superCat.totalProducts})</span>
            </div>

            {catSections.map(category => (
              <div key={category.id} className="mb-7">
                <div className="flex items-center gap-3 py-3 border-b border-slate-200 mb-4">
                  <span className="font-semibold text-sm text-slate-800 uppercase tracking-wide flex-1">{category.name}</span>
                  <span className="inline-block bg-indigo-500 text-white font-semibold px-2.5 py-1 rounded-full text-xs min-w-[24px] text-center">
                    {category.products.length}
                  </span>
                </div>
                <div style={isMobile ? { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px' } : { display: 'grid', gridTemplateColumns: `repeat(auto-fill, minmax(${148 * (cardSize || 1)}px, 1fr))`, gap: `${10 * (cardSize || 1)}px` }}>
                  {category.products.map(product => (
                    <ProductCard key={product.id} product={product} isFavorited={isFavorited(product.id)} inCart={isInCart(product.id)}
                      onProductSelected={onProductSelected} onAddToCart={onAddToCart} onToggleFavorite={onToggleFavorite} cardSize={isMobile ? 1 : cardSize} />
                  ))}
                </div>
              </div>
            ))}
          </div>
        )
      })}
    </div>
  )
}

export default CategoryView

// src/components/CategoryView.vue
<template>
  <div class="category-view">
    <div v-if="loading" class="loading">Loading categories...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <div v-else>
      <!-- Super Category Loop (e.g., "Noodles & Rice") -->
      <div 
        v-for="superCat in hierarchy" 
        :key="superCat.id"
        class="super-category-page"
      >
        <!-- Super Category Header -->
        <div class="super-cat-header">
          <span class="super-cat-emoji">{{ superCat.emoji }}</span>
          <h2 class="super-cat-title">{{ superCat.name }}</h2>
          <span class="super-cat-count">({{ superCat.totalProducts }})</span>
        </div>

        <!-- Category Sections (e.g., "XWX Snack Noodles", "Buldak Chips & Snacks") -->
        <div 
          v-for="category in getProductsByCategory(superCat.id)"
          :key="category.id"
          class="category-section"
        >
          <div class="category-header">
            <span class="category-name">{{ category.name }}</span>
            <span class="category-count">{{ category.products.length }}</span>
          </div>

          <div class="products-scroll">
            <div class="products-grid-horizontal">
              <ProductCard
                v-for="product in category.products"
                :key="product.id"
                :product="product"
                :is-favorited="isFavorited(product.id)"
                :in-cart="isInCart(product.id)"
                @product-selected="$emit('product-selected', product)"
                @add-to-cart="$emit('add-to-cart', product)"
                @toggle-favorite="$emit('toggle-favorite', product)"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ProductCard from './ProductCard.vue'

export default {
  name: 'CategoryView',
  components: { ProductCard },
  props: {
    products: {
      type: Array,
      default: () => []
    },
    favorites: {
      type: Array,
      default: () => []
    },
    cart: {
      type: Array,
      default: () => []
    }
  },
  emits: ['product-selected', 'add-to-cart', 'toggle-favorite'],
  data() {
    return {
      hierarchy: [],
      loading: true,
      error: null
    }
  },
  computed: {
    isFavorited() {
      return (productId) => this.favorites.some(fav => fav.id === productId)
    },
    isInCart() {
      return (productId) => this.cart.some(item => item.id === productId)
    }
  },
  methods: {
    async loadCategories() {
      try {
        this.loading = true
        const response = await fetch('/api/categories/hierarchy')
        if (!response.ok) throw new Error('Failed to load categories')
        
        const data = await response.json()
        this.hierarchy = data.hierarchy || []
        
        this.error = null
      } catch (err) {
        this.error = 'Error loading categories: ' + err.message
        console.error('CategoryView error:', err)
      } finally {
        this.loading = false
      }
    },
    getProductsByCategory(superCatId) {
      // Group products by category within a super_category
      const grouped = {}
      
      this.products.forEach(product => {
        if (product.super_category_id !== superCatId) return
        
        const catId = product.category_id
        const catName = product.category || 'Uncategorized'
        
        if (!grouped[catId]) {
          grouped[catId] = {
            id: catId,
            name: catName,
            products: []
          }
        }
        grouped[catId].products.push(product)
      })
      
      // Sort categories by name, then products by name
      return Object.values(grouped)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map(cat => ({
          ...cat,
          products: cat.products.sort((a, b) => a.name.localeCompare(b.name))
        }))
    }
  },
  watch: {
    products: {
      immediate: true,
      handler() {
        this.loadCategories()
      }
    }
  }
}
</script>

<style scoped>
.category-view {
  width: 100%;
}

.loading, .error {
  padding: 40px 20px;
  text-align: center;
  font-size: 16px;
  color: #666;
}

.error {
  color: #c0392b;
}

/* Super Category Page */
.super-category-page {
  margin-bottom: 40px;
}

.super-cat-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 24px;
  padding-bottom: 16px;
  border-bottom: 2px solid #e2ddd8;
}

.super-cat-emoji {
  font-size: 28px;
}

.super-cat-title {
  font-size: 24px;
  font-weight: 600;
  color: #1a1a18;
  margin: 0;
}

.super-cat-count {
  font-size: 16px;
  color: #5a5750;
  margin-left: auto;
}

/* Category Section */
.category-section {
  margin-bottom: 28px;
}

.category-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 0;
  border-bottom: 1px solid #e2ddd8;
  margin-bottom: 16px;
}

.category-name {
  font-weight: 600;
  font-size: 14px;
  color: #1a1a18;
  text-transform: uppercase;
  letter-spacing: 0.3px;
  flex: 1;
}

.category-count {
  display: inline-block;
  background: #c0392b;
  color: white;
  font-weight: 600;
  padding: 4px 10px;
  border-radius: 12px;
  font-size: 12px;
  min-width: 24px;
  text-align: center;
}

/* Products Grid (Wrapped Layout) */
.products-scroll {
  overflow: visible;
  padding-bottom: 8px;
  margin-bottom: 8px;
}

.products-grid-horizontal {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(calc(148px * var(--card-scale, 1)), 1fr));
  gap: calc(10px * var(--card-scale, 1));
  padding: 0;
  width: 100%;
}

@media (max-width: 640px) {
  .super-cat-header {
    gap: 8px;
    margin-bottom: 16px;
  }

  .super-cat-emoji {
    font-size: 20px;
  }

  .super-cat-title {
    font-size: 18px;
  }

  .super-cat-count {
    font-size: 14px;
  }

  .category-section {
    margin-bottom: 20px;
  }

  .category-header {
    padding: 10px 0;
    margin-bottom: 12px;
  }

  .category-name {
    font-size: 13px;
  }

  .category-count {
    font-size: 11px;
    padding: 3px 8px;
  }

  .products-grid-horizontal {
    grid-template-columns: repeat(2, 1fr);
    gap: 8px;
  }
}
</style>
